import type { ComponentType } from 'react'
import type { SectionKey, TemplateMeta } from '../core/types'
import type { TemplateProps } from './primitives'
import {
  AmazonTemplate,
  BainTemplate,
  BcgTemplate,
  BitsTemplate,
  CambridgeTemplate,
  ChronologicalTemplate,
  CreativeTemplate,
  CvAcademicLongTemplate,
  CvEuropeanExtendedTemplate,
  CvResearchModernTemplate,
  DeedyTemplate,
  DtuTemplate,
  EuropassTemplate,
  ExecTemplate,
  FederalTemplate,
  FunctionalTemplate,
  GoldmanTemplate,
  GoogleTemplate,
  HarvardTemplate,
  IimTemplate,
  IiitTemplate,
  IitbTemplate,
  IitkgpTemplate,
  InseadTemplate,
  IsbTemplate,
  JakeTemplate,
  McKinseyTemplate,
  MetaTemplate,
  MicrosoftTemplate,
  MitTemplate,
  NetflixTemplate,
  NitTemplate,
  OxfordTemplate,
  PlainTemplate,
  ResearchTemplate,
  StanfordTemplate,
  WhartonTemplate,
} from './layouts'

export interface TemplateEntry extends TemplateMeta {
  Component: ComponentType<TemplateProps>
}

const CAMPUS_SECTIONS: SectionKey[] = [
  'education',
  'experience',
  'projects',
  'skills',
  'achievements',
  'positions',
  'extracurriculars',
]

const CAMPUS_WITH_CERTS: SectionKey[] = [...CAMPUS_SECTIONS, 'certifications']

const BIGTECH_SECTIONS: SectionKey[] = [
  'experience',
  'projects',
  'skills',
  'education',
  'achievements',
  'certifications',
]

const MBA_SECTIONS: SectionKey[] = [
  'education',
  'experience',
  'positions',
  'achievements',
  'skills',
  'languages',
  'certifications',
]

const CV_SECTIONS: SectionKey[] = [
  'education',
  'experience',
  'publications',
  'grants',
  'teaching',
  'talks',
  'service',
  'achievements',
  'skills',
  'languages',
]

const EURO_SECTIONS: SectionKey[] = [
  'education',
  'experience',
  'projects',
  'publications',
  'skills',
  'languages',
  'achievements',
]

const CONSERVATIVE_SECTIONS: SectionKey[] = [
  'education',
  'experience',
  'projects',
  'skills',
  'achievements',
  'languages',
]

export const TEMPLATES: TemplateEntry[] = [
  /* -- v1 (kept) ---------------------------------------------------------- */
  {
    id: 'jake',
    name: "Jake's Resume",
    origin: 'Jake Gutierrez · Overleaf',
    blurb:
      'The single most-used LaTeX resume on the internet. Centred header, hairline rules, brutally efficient one page.',
    flairs: ['swe', 'student', 'intern', 'one-page', 'dense', 'photo-free', 'us'],
    sections: ['education', 'experience', 'projects', 'skills', 'achievements'],
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#111827',
    Component: JakeTemplate,
  },
  {
    id: 'deedy',
    name: 'Deedy Two-Column',
    origin: 'Debarghya Das',
    blurb:
      'Sidebar for education and skills, wide column for impact. Fits ~30% more content per page than a single column.',
    flairs: ['swe', 'data', 'student', 'two-column', 'dense', 'photo-free', 'us'],
    sections: ['education', 'experience', 'projects', 'skills', 'achievements', 'certifications', 'languages'],
    requiredSections: ['education', 'skills'],
    columns: 2,
    atsScore: 'good',
    accent: '#0b7285',
    Component: DeedyTemplate,
  },
  {
    id: 'harvard',
    name: 'Harvard OCS',
    origin: 'Harvard Office of Career Services',
    blurb:
      'The conservative gold standard. Small-caps header, ruled sections, zero decoration. Safe in front of any reader.',
    flairs: ['consulting', 'non-tech', 'research', 'student', 'one-page', 'airy', 'photo-free', 'us'],
    sections: ['education', 'experience', 'projects', 'positions', 'skills', 'languages'],
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#a51c30',
    Component: HarvardTemplate,
  },
  {
    id: 'mit',
    name: 'MIT Engineering',
    origin: 'MIT Career Advising',
    blurb:
      'Left-aligned header with a crimson rule under every section. Built for engineering and research-heavy histories.',
    flairs: ['swe', 'core-eng', 'research', 'student', 'one-page', 'dense', 'us'],
    sections: ['education', 'experience', 'projects', 'publications', 'skills', 'achievements'],
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#750014',
    Component: MitTemplate,
  },
  {
    id: 'stanford',
    name: 'Stanford Modern',
    origin: 'Stanford BEAM',
    blurb:
      'Experience-first with a short profile up top. The right shape once you have real work history to lead with.',
    flairs: ['swe', 'product', 'design', 'mid', 'one-page', 'airy', 'us'],
    sections: ['experience', 'education', 'projects', 'skills', 'achievements'],
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#8c1515',
    Component: StanfordTemplate,
  },
  {
    id: 'iitb',
    name: 'IIT Bombay Campus',
    origin: 'IIT Bombay Placement Cell',
    blurb:
      'Shaded section bars and the marks table placement cells expect. Optimised for the one-page campus deadline.',
    flairs: ['swe', 'core-eng', 'data', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_SECTIONS,
    requiredSections: ['education', 'achievements'],
    columns: 1,
    atsScore: 'good',
    accent: '#333333',
    Component: IitbTemplate,
  },
  {
    id: 'iitkgp',
    name: 'IIT Kharagpur Standard',
    origin: 'IIT Kharagpur CDC',
    blurb:
      'Centred header, education table, achievements promoted above internships — the CDC-mandated ordering.',
    flairs: ['swe', 'core-eng', 'consulting', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_SECTIONS,
    requiredSections: ['education', 'achievements'],
    columns: 1,
    atsScore: 'good',
    accent: '#222222',
    Component: IitkgpTemplate,
  },
  {
    id: 'nit',
    name: 'NIT Jamshedpur',
    origin: 'NIT Jamshedpur T&P Cell',
    blurb:
      'Split header with contact block on the right, navy accents, and room for certifications alongside training.',
    flairs: ['core-eng', 'swe', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_WITH_CERTS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'good',
    accent: '#10316b',
    Component: NitTemplate,
  },
  {
    id: 'plain',
    name: 'Plain ATS',
    origin: 'Resume Forge',
    blurb:
      'Maximum machine readability. Standard headings, no columns, no rules, no glyphs. Use it when the posting screams "portal".',
    flairs: ['non-tech', 'marketing', 'swe', 'mid', 'senior', 'airy', 'photo-free', 'us', 'europe'],
    sections: [
      'experience',
      'education',
      'projects',
      'skills',
      'certifications',
      'achievements',
      'languages',
    ],
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#374151',
    Component: PlainTemplate,
  },
  {
    id: 'exec',
    name: 'Executive Brief',
    origin: 'Resume Forge',
    blurb:
      'Dark header band, summary-led, achievements pulled out of the role bullets. For senior and leadership applications.',
    flairs: ['senior', 'product', 'consulting', 'non-tech', 'marketing', 'airy', 'europe', 'us'],
    sections: ['experience', 'achievements', 'skills', 'education', 'certifications', 'positions', 'languages'],
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'fair',
    accent: '#1f2937',
    Component: ExecTemplate,
  },
  {
    id: 'research',
    name: 'Academic CV',
    origin: 'Resume Forge',
    blurb:
      'Publications directly under education, grants and awards given their own block. Grows past one page on purpose.',
    flairs: ['research', 'data', 'senior', 'airy', 'photo-free', 'europe', 'us'],
    sections: [
      'education',
      'publications',
      'experience',
      'achievements',
      'projects',
      'skills',
      'languages',
      'positions',
    ],
    requiredSections: ['education', 'publications'],
    columns: 1,
    atsScore: 'good',
    accent: '#374151',
    Component: ResearchTemplate,
  },

  /* -- v2 additions: FAANG / Big Tech ------------------------------------ */
  {
    id: 'google',
    name: 'Google New Grad',
    origin: 'Google University Recruiting guides',
    blurb:
      'Colour-blocked header with tight typography. What Google engineers submit for internal transfers and referrals.',
    flairs: ['swe', 'data', 'intern', 'student', 'mid', 'one-page', 'photo-free', 'us'],
    sections: BIGTECH_SECTIONS,
    requiredSections: ['experience', 'skills'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#4285f4',
    Component: GoogleTemplate,
  },
  {
    id: 'meta',
    name: 'Meta Engineering',
    origin: 'Meta university brand guide',
    blurb:
      'Facebook-blue accent bar over a single-column body. Rewards impact bullets that lead with metrics.',
    flairs: ['swe', 'data', 'mid', 'senior', 'one-page', 'dense', 'us'],
    sections: BIGTECH_SECTIONS,
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#1877f2',
    Component: MetaTemplate,
  },
  {
    id: 'amazon',
    name: 'Amazon LP-Aligned',
    origin: 'Amazon Career hub template',
    blurb:
      'STAR-friendly single column. The header stays plain so leadership-principles bullets do the talking.',
    flairs: ['swe', 'product', 'non-tech', 'mid', 'senior', 'one-page', 'photo-free', 'us'],
    sections: BIGTECH_SECTIONS,
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#ff9900',
    Component: AmazonTemplate,
  },
  {
    id: 'microsoft',
    name: 'Microsoft Segoe',
    origin: 'Microsoft Careers style',
    blurb:
      'Understated blue bar, Segoe-ish sans, dense one page. What Microsoft recruiters see all day and read cleanly.',
    flairs: ['swe', 'core-eng', 'mid', 'one-page', 'dense', 'us'],
    sections: BIGTECH_SECTIONS,
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#0078d4',
    Component: MicrosoftTemplate,
  },
  {
    id: 'netflix',
    name: 'Netflix Minimal',
    origin: 'Netflix Culture memo aesthetic',
    blurb:
      'Deep red rule, ultra-minimal typography. Skips the summary — Netflix engineers rarely write one.',
    flairs: ['swe', 'senior', 'one-page', 'airy', 'us'],
    sections: BIGTECH_SECTIONS,
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#e50914',
    Component: NetflixTemplate,
  },

  /* -- v2 additions: Consulting / Finance -------------------------------- */
  {
    id: 'mckinsey',
    name: 'McKinsey PST',
    origin: 'McKinsey campus template',
    blurb:
      'Small-caps section heads, no colour, achievements ahead of skills. The format PST-track candidates submit.',
    flairs: ['consulting', 'non-tech', 'senior', 'mid', 'airy', 'photo-free', 'us', 'europe'],
    sections: CONSERVATIVE_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#003a70',
    Component: McKinseyTemplate,
  },
  {
    id: 'bcg',
    name: 'BCG Two-Column',
    origin: 'Boston Consulting Group EMEA guide',
    blurb:
      'Left sidebar for education and languages, main column for strategy engagements. Green accents throughout.',
    flairs: ['consulting', 'non-tech', 'mid', 'senior', 'two-column', 'europe', 'us'],
    sections: [...CONSERVATIVE_SECTIONS, 'languages', 'certifications'],
    requiredSections: ['education', 'experience'],
    columns: 2,
    atsScore: 'good',
    accent: '#0e7c66',
    Component: BcgTemplate,
  },
  {
    id: 'bain',
    name: 'Bain Sidebar',
    origin: 'Bain & Company case-team template',
    blurb:
      'Red-accented sidebar layout tuned for consulting cases and MBB interview loops.',
    flairs: ['consulting', 'mid', 'senior', 'two-column', 'europe', 'us'],
    sections: [...CONSERVATIVE_SECTIONS, 'languages', 'certifications'],
    requiredSections: ['education', 'experience'],
    columns: 2,
    atsScore: 'good',
    accent: '#cc0000',
    Component: BainTemplate,
  },
  {
    id: 'goldman',
    name: 'Goldman IBD',
    origin: 'Goldman Sachs Investment Banking format',
    blurb:
      'Dense, tightly-ruled single column, right-aligned dates in bold. Every millimetre packed with signal.',
    flairs: ['consulting', 'non-tech', 'mid', 'senior', 'one-page', 'dense', 'us'],
    sections: CONSERVATIVE_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#7399c6',
    Component: GoldmanTemplate,
  },
  {
    id: 'wharton',
    name: 'Wharton MBA',
    origin: 'Wharton MBA Career Management',
    blurb:
      'Education front and centre, quantified achievements block, extra room for leadership. Two pages when needed.',
    flairs: ['consulting', 'non-tech', 'product', 'mid', 'senior', 'airy', 'us'],
    sections: [...MBA_SECTIONS, 'projects'],
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#a41a37',
    Component: WhartonTemplate,
  },

  /* -- v2 additions: Indian campus + MBA --------------------------------- */
  {
    id: 'bits',
    name: 'BITS Pilani Standard',
    origin: 'BITS Pilani Placement Unit',
    blurb:
      'The compact single-page BITSian format with a marks table and Practice School experience up top.',
    flairs: ['swe', 'core-eng', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_WITH_CERTS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'good',
    accent: '#00539c',
    Component: BitsTemplate,
  },
  {
    id: 'dtu',
    name: 'DTU Delhi',
    origin: 'Delhi Technological University T&P Cell',
    blurb:
      'Standard DTU campus format with certifications section. Works for both circuit and non-circuit branches.',
    flairs: ['core-eng', 'swe', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_WITH_CERTS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'good',
    accent: '#231f20',
    Component: DtuTemplate,
  },
  {
    id: 'iiit',
    name: 'IIIT Campus',
    origin: 'IIIT-H / IIIT-B placement office',
    blurb:
      'What IIIT students hand in for tech placements — CS-heavy with room for research and open-source projects.',
    flairs: ['swe', 'data', 'research', 'student', 'intern', 'one-page', 'dense', 'india'],
    sections: CAMPUS_WITH_CERTS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'good',
    accent: '#5b2c6f',
    Component: IiitTemplate,
  },
  {
    id: 'iim',
    name: 'IIM Ahmedabad',
    origin: 'IIM Ahmedabad Placement Committee',
    blurb:
      'MBA-standard format leading with education and academic achievements. Leadership section pulled out separately.',
    flairs: ['consulting', 'product', 'non-tech', 'mid', 'senior', 'one-page', 'india'],
    sections: MBA_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#7b1e29',
    Component: IimTemplate,
  },
  {
    id: 'isb',
    name: 'ISB Hyderabad',
    origin: 'Indian School of Business CAS',
    blurb:
      'Post-experience MBA layout — professional experience first, then ISB PGP, then leadership highlights.',
    flairs: ['consulting', 'product', 'non-tech', 'senior', 'one-page', 'india'],
    sections: MBA_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#003057',
    Component: IsbTemplate,
  },

  /* -- v2 additions: European / International ---------------------------- */
  {
    id: 'oxford',
    name: 'Oxford Academic',
    origin: 'University of Oxford Careers Service',
    blurb:
      'British academic CV: personal statement, then education, then research and publications. Grows to two pages naturally.',
    flairs: ['research', 'consulting', 'senior', 'airy', 'photo-free', 'europe'],
    sections: EURO_SECTIONS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#002147',
    Component: OxfordTemplate,
  },
  {
    id: 'cambridge',
    name: 'Cambridge CV',
    origin: 'University of Cambridge Careers Service',
    blurb:
      'Cambridge Careers Service reference format. Same discipline as Oxford, slightly denser typographic setup.',
    flairs: ['research', 'consulting', 'senior', 'airy', 'photo-free', 'europe'],
    sections: EURO_SECTIONS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#a3c1ad',
    Component: CambridgeTemplate,
  },
  {
    id: 'insead',
    name: 'INSEAD MBA',
    origin: 'INSEAD Career Development Centre',
    blurb:
      'Bilingual-friendly European MBA layout. Languages block is first-class; role bullets are quantified.',
    flairs: ['consulting', 'product', 'non-tech', 'senior', 'airy', 'europe'],
    sections: MBA_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#1c2b4a',
    Component: InseadTemplate,
  },
  {
    id: 'europass',
    name: 'Europass CV',
    origin: 'European Commission Europass',
    blurb:
      'Simplified Europass-style layout. Skips the sidebar and photo box that break parsers, keeps the section ordering.',
    flairs: ['non-tech', 'research', 'mid', 'senior', 'airy', 'photo-free', 'europe'],
    sections: EURO_SECTIONS,
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#003399',
    Component: EuropassTemplate,
  },

  /* -- v2 additions: Format variants ------------------------------------- */
  {
    id: 'chronological',
    name: 'Reverse Chronological',
    origin: 'Resume Forge',
    blurb:
      'The classic North-American format: summary, career history newest first, then education. Nothing fancy.',
    flairs: ['non-tech', 'marketing', 'swe', 'mid', 'senior', 'one-page', 'photo-free', 'us'],
    sections: ['experience', 'education', 'skills', 'certifications'],
    requiredSections: ['experience'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#1f2937',
    Component: ChronologicalTemplate,
  },
  {
    id: 'functional',
    name: 'Functional / Skills-First',
    origin: 'Resume Forge',
    blurb:
      'Skills and selected work up top, employment history relegated below. For career switchers and portfolio-led roles.',
    flairs: ['design', 'marketing', 'non-tech', 'mid', 'one-page', 'airy', 'us'],
    sections: ['skills', 'projects', 'experience', 'education', 'certifications'],
    requiredSections: ['skills'],
    columns: 1,
    atsScore: 'good',
    accent: '#334155',
    Component: FunctionalTemplate,
  },
  {
    id: 'federal',
    name: 'US Federal Long-Form',
    origin: 'USAJOBS resume builder',
    blurb:
      'The verbose format US federal postings expect. Detailed responsibilities, all coursework, no length cap.',
    flairs: ['non-tech', 'research', 'senior', 'airy', 'photo-free', 'us'],
    sections: [
      'experience',
      'education',
      'skills',
      'certifications',
      'achievements',
      'positions',
      'publications',
    ],
    requiredSections: ['experience', 'education'],
    columns: 1,
    atsScore: 'excellent',
    accent: '#1a3a63',
    Component: FederalTemplate,
  },
  {
    id: 'creative',
    name: 'Creative Sidebar',
    origin: 'Resume Forge',
    blurb:
      'Sidebar with contact and skills, main column for portfolio work. For design, marketing and product roles.',
    flairs: ['design', 'product', 'marketing', 'mid', 'two-column', 'airy', 'us', 'europe'],
    sections: ['experience', 'projects', 'skills', 'education', 'achievements', 'languages'],
    requiredSections: ['experience'],
    columns: 2,
    atsScore: 'fair',
    accent: '#7c3aed',
    Component: CreativeTemplate,
  },

  /* -- v3 additions: CV templates (beta) --------------------------------- */
  {
    id: 'cv-academic-long',
    name: 'Academic CV — Long-form',
    origin: 'Resume Forge · academic reference',
    blurb:
      'The long US academic CV: research statement, appointments, publications, grants, teaching, service. Multi-page by design.',
    flairs: ['research', 'senior', 'airy', 'photo-free', 'us', 'europe'],
    sections: CV_SECTIONS,
    requiredSections: ['education', 'publications'],
    columns: 1,
    atsScore: 'good',
    accent: '#0f172a',
    kind: 'cv',
    beta: true,
    Component: CvAcademicLongTemplate,
  },
  {
    id: 'cv-research-modern',
    name: 'Research CV — Modern',
    origin: 'Resume Forge · modern research layout',
    blurb:
      'Cleaner sans-serif take on the research CV — for postdocs, industrial research and applied ML roles.',
    flairs: ['research', 'data', 'mid', 'senior', 'airy', 'photo-free', 'us', 'europe'],
    sections: CV_SECTIONS,
    requiredSections: ['education'],
    columns: 1,
    atsScore: 'good',
    accent: '#1e40af',
    kind: 'cv',
    beta: true,
    Component: CvResearchModernTemplate,
  },
  {
    id: 'cv-european-extended',
    name: 'European CV — Extended',
    origin: 'Resume Forge · European academic conventions',
    blurb:
      'Long-form European academic CV. Includes personal statement, grants, teaching and community service — as EU reviewers expect.',
    flairs: ['research', 'non-tech', 'senior', 'airy', 'photo-free', 'europe'],
    sections: [...CV_SECTIONS, 'projects', 'certifications', 'extracurriculars'],
    requiredSections: ['education', 'experience'],
    columns: 1,
    atsScore: 'good',
    accent: '#003399',
    kind: 'cv',
    beta: true,
    Component: CvEuropeanExtendedTemplate,
  },
]

export const TEMPLATE_MAP = new Map(TEMPLATES.map((t) => [t.id, t]))

export function getTemplate(id: string | null | undefined): TemplateEntry {
  return (id && TEMPLATE_MAP.get(id)) || TEMPLATES[0]
}
